name: zef_log_core
description: A versatile and extensible logging framework for Dart applications, providing configurable log levels, custom formatting, and adaptable output options.
version: 0.0.1
homepage: https://www.zooper.dev
repository: https://github.com/zooper-lib/ZEF_Log_Core
topics:
  - logging
  - log
  - abstractions
funding:
  - https://buymeacoffee.com/zooperlib

environment:
  sdk: ^3.0.5

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
